# This is a basic workflow to help you get started with Actions

name: ncov_dailyup_autorun

# Controls when the workflow will run
on:
  schedule:
   - cron: "8/10 4,10,22 * * *"
  # Triggers the workflow on push
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check code.
        uses: actions/checkout@v2

      # Setup python3
      - name: Install python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: 3.8

      # Install requests
      - name: Install requests
        run: 
          pip install --upgrade requests

      # Runs a single command using the runners shell
      - name: Run main.py
        run: python3 main.py
        env:
          BUPT_USERNAME: ${{secrets.BUPT_USERNAME}}
          BUPT_PASSWORD: ${{secrets.BUPT_PASSWORD}}
